security:
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  application:
    name: redisapp
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
    password: password