security:
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  application:
    name: redisapp
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ppr
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

